### ISSUE TITLE
SIG Release Github team hygiene

### ISSUE THREAD

**Issue by justaugustus** [kubernetes/sig-release#353]
Some action items for @tpepper and I once https://github.com/kubernetes/community/pull/2778 merges.

- [x] (@calebamiles / @jdumars) Grant Tim and Stephen maintainer status for the following teams:
  - kubernetes-milestone-maintainers
  - kubernetes-release-managers
  - release-admins
  - release-maintainers
  - sig-release-admins
  - sig-release-api-reviews
  - sig-release-bugs
  - sig-release-feature-requests
  - sig-release-members
  - sig-release-misc
  - sig-release-pr-reviews
  - sig-release-proposals
  - sig-release-test-failures
- [x] Prune `kubernetes-milestone-maintainers` - #241
- [x] Prune `kubernetes-release-managers`
- [x] Remove unused teams
  - release-admins
  - release-maintainers
  - sig-release-api-reviews
  - sig-release-bugs
  - sig-release-feature-requests
  - sig-release-misc
  - sig-release-pr-reviews
  - sig-release-proposals
  - sig-release-test-failures
- [x] Update all SIG Release Github teams
  - [x] Update `sig-release-members` team with all current and previous release team members (rel: https://github.com/kubernetes/sig-release/pull/348#discussion_r227642396)
- [x] Update contact details in `k/community` - https://github.com/kubernetes/community/pull/2941

**Comment by justaugustus** [comment]
@calebamiles / @jdumars -- Can you grant Tim and I access to these groups when you have a chance?

**Comment by calebamiles** [comment]
done
/close

**Comment by justaugustus** [comment]
Still some cleanup to do on this one, now that Tim and I have access.
/reopen
/unassign @calebamiles @jdumars

**Comment by idvoretskyi** [comment]
/reopen

@kubernetes/sig-release mailing lists still exist. I can delete them after the explicit approval from at least one SIG chair.

REF: https://github.com/kubernetes/community/issues/2324#issuecomment-462736648

**Comment by justaugustus** [comment]
@idvoretskyi -- which of the SIG Release lists still exist?

**Comment by idvoretskyi** [comment]
@justaugustus it's fine now, we can close.

/close

**Comment by justaugustus** [comment]
There's still a little investigation I need to do around our Google Group moderation settings, so I'm reopening. :)
/reopen

**Comment by justaugustus** [comment]
nvm, I just realized this is only for GitHub teams. :stuck_out_tongue_closed_eyes: 
/close
